n=input("Digite algo:")
print("O tipo primitvo desse valor é", type(n))
print("Só tem espaço", n.isspace())
print("É um número?",n.isnumeric())
print("É alfabeto?", n.isalpha())
print("É alfanumérico?", n.isalnum())
print("Está em maiusculas?",n.isupper())
print("Está em minusculas?",n.islower())