a=input("Digite algo: ")
print(a.isnumeric())
print(a.isdecimal())
print(a.isupper())
print(a.isspace())
print(a.istitle())
print(a.isalnum())
print(a.isalpha())
print(a.isascii())
print(a.isdigit())
print(a.isidentifier())