n1=int(input('Digite o valor: '))
print('A tabuada de 1 é: {}'.format(n1*1))
print('A tabuada de 2 é: {}'.format(n1*2))
print('A tabuada de 3 é: {}'.format(n1*3))
print('A tabuada de 4 é: {}'.format(n1*4))
print('A tabuada de 5 é: {}'.format(n1*5))
print('A tabuada de 6 é: {}'.format(n1*6))
print('A tabuada de 7 é: {}'.format(n1*7))
print('A tabuada de 8 é: {}'.format(n1*8))
print('A tabuada de 9 é: {}'.format(n1*9))
print('A tabuada de 10 é: {}'.format(n1*10))
